### ISSUE TITLE
Limit is overruled by paginate

### ISSUE THREAD

**Issue by matthijsgroen** [dashofcode/tracker_api#13]
When I just want the 2 first unstarted stories, I get all of them. I think it is because the limit I set is overruled by the paginate method of the endpoint.

**Comment by bartoszkopinski** [comment]
@forest this behaviour is confusing since there is no mention of `auto_paginate` in the readme but it's enabled by default.

Additionally, `limit` option is mentioned but will not work by default like this:
> ```
> project.stories(with_state: :unscheduled, limit: 10) # Get 10 unscheduled stories for a project
> ```

This will by default return all stories.

I think `auto_paginate` should be disabled automatically if `limit` is provided.
